<?php

use \Drupal\custom_entity_examples\Entity\BlogInterface;

/**
 * @file
 * Contains custom_entity_examples.module.
 */

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function custom_entity_examples_cex_blog_insert(BlogInterface $blog) {
  if (!is_null(Drupal::config('core.extension')->get('module')['custom_entity_alias'])) {
    $view = \Drupal::entityTypeManager()
      ->getStorage('view')
      ->load('posts');
    Drupal::service('views.alias_generator')
      ->generateViewAlias($view, $blog, [
        'alias' => 'field_title',
      ]);
  }
}
