<?php

/**
 * @file
 * Contains custom_entity_ui.module.
 */

use Drupal\Core\Entity\ContentEntityFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function custom_entity_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help.
    case 'help.page.custom_entity_ui':
      return t('<h3>About</h3><p>The Custom Entity UI module provides an admin interface for custom entity types.</p>');
    default:
      return '';
  }
}

/**
 * Implements hook_form_alter().
 */
function custom_entity_ui_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (is_a($form_state->getFormObject(), ContentEntityFormInterface::class)) {
    /** @var \Drupal\Core\Entity\EntityFormInterface $entity_form */
    $entity_form = $form_state->getFormObject();

    if ($entity_form->getEntity()->getEntityTypeId() === 'entity_form_display') {
      // Add form display form element.
      /** @var \Drupal\Core\Entity\Display\EntityFormDisplayInterface $form_display */
      $form_display = $entity_form->getEntity();

      $form['advanced'] = [
        '#type' => 'details',
        '#title' => t('Advanced settings'),
        'redirect_destination' => [
          '#type' => 'textfield',
          '#title' => t('Redirect destination'),
          '#description' => t('Route to redirect to after successful form submission.'),
          '#default_value' => $form_display
            ->getThirdPartySetting('custom_entity', 'redirect_destination'),
        ],
      ];

      $form['#entity_builders'][] = 'save_advanced_settings';
    }
    else {
      // Add entity form submit handler.
      $form['actions']['submit']['#submit'][] = 'redirect_on_success';
    }
  }
}

/**
 * Entity builder callback saving advanced settings as received from then form.
 *
 * @param string $entity_type_id
 *   The entity type ID, i.e. 'entity_form_display'.
 * @param \Drupal\Core\Config\Entity\ConfigEntityInterface $entity
 *   The display form entity, i.e. the display form entity.
 * @param array $form
 *   The renderable display form settings form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The display form settings form state.
 */
function save_advanced_settings(string $entity_type_id, \Drupal\Core\Config\Entity\ConfigEntityInterface $entity, array &$form, FormStateInterface &$form_state) {
  if ($redirect_destination = $form_state->getValue('redirect_destination')) {
    $entity->setThirdPartySetting('custom_entity', 'redirect_destination', $redirect_destination);
  }
  else {
    $entity->unsetThirdPartySetting('custom_entity', 'redirect_destination');
  }
}

/**
 * Submit handler for entity forms.
 *
 * @param array $form
 *   The renderable form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function redirect_on_success(array &$form, FormStateInterface $form_state) {
  $redirect_destination = $form_state
    ->getFormObject()
    ->getFormDisplay($form_state)
    ->getThirdPartySetting('custom_entity', 'redirect_destination');
  if ($redirect_destination) {
    $form_state->setRedirectUrl(Url::fromRoute($redirect_destination));
  }
}

///**
// * Implements hook_menu_local_actions_alter().
// */
//function custom_entity_ui_menu_local_actions_alter(&$local_actions) {
//  $local_action_builders = Drupal::service('local_action_builder.entity.collector')->getLocalEntityActionBuilders();
//  foreach (Drupal::entityTypeManager()->getDefinitions() as $entity_type) {
//    /** @var \Drupal\custom_entity_ui\Menu\LocalEntityActionBuilderInterface $action_builder */
//    foreach ($local_action_builders as $action_builder) {
//      if ($action_builder->applies($entity_type)) {
//        $local_action = $action_builder->buildLocalAction($entity_type);
//        $local_actions[$local_action['id']] = $local_action;
//      }
//    }
//  }
//}
